# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0egapido.auth.v1\"\"\n\x11RequestOtpRequest\x12\r\n\x05phone\x18\x01 \x01(\t\"=\n\x12RequestOtpResponse\x12\x12\n\nexpires_in\x18\x01 \x01(\x05\x12\x13\n\x0bretry_after\x18\x02 \x01(\x05\"/\n\x10VerifyOtpRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"&\n\rLogoutRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"!\n\x0eLogoutResponse\x12\x0f\n\x07revoked\x18\x01 \x01(\x08\"g\n\tTokenPair\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x19\n\x11\x61\x63\x63\x65ss_expires_in\x18\x03 \x01(\x05\x12\x12\n\ntoken_type\x18\x04 \x01(\t2\xc5\x02\n\x0b\x41uthService\x12S\n\nRequestOtp\x12!.gapido.auth.v1.RequestOtpRequest\x1a\".gapido.auth.v1.RequestOtpResponse\x12H\n\tVerifyOtp\x12 .gapido.auth.v1.VerifyOtpRequest\x1a\x19.gapido.auth.v1.TokenPair\x12N\n\x0cRefreshToken\x12#.gapido.auth.v1.RefreshTokenRequest\x1a\x19.gapido.auth.v1.TokenPair\x12G\n\x06Logout\x12\x1d.gapido.auth.v1.LogoutRequest\x1a\x1e.gapido.auth.v1.LogoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTOTPREQUEST']._serialized_start=30
  _globals['_REQUESTOTPREQUEST']._serialized_end=64
  _globals['_REQUESTOTPRESPONSE']._serialized_start=66
  _globals['_REQUESTOTPRESPONSE']._serialized_end=127
  _globals['_VERIFYOTPREQUEST']._serialized_start=129
  _globals['_VERIFYOTPREQUEST']._serialized_end=176
  _globals['_REFRESHTOKENREQUEST']._serialized_start=178
  _globals['_REFRESHTOKENREQUEST']._serialized_end=222
  _globals['_LOGOUTREQUEST']._serialized_start=224
  _globals['_LOGOUTREQUEST']._serialized_end=262
  _globals['_LOGOUTRESPONSE']._serialized_start=264
  _globals['_LOGOUTRESPONSE']._serialized_end=297
  _globals['_TOKENPAIR']._serialized_start=299
  _globals['_TOKENPAIR']._serialized_end=402
  _globals['_AUTHSERVICE']._serialized_start=405
  _globals['_AUTHSERVICE']._serialized_end=730
# @@protoc_insertion_point(module_scope)
