# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """Passwordless phone + OTP authentication.

    Flow:
    1. RequestOtp(phone)          -> OTP is queued to RabbitMQ and delivered by SMS.
    2. VerifyOtp(phone, code)     -> creates the user on first login, returns token pair.
    3. RefreshToken(refresh)      -> rotates the refresh token, returns a new pair.
    4. Logout(refresh)            -> revokes the refresh token family.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestOtp = channel.unary_unary(
                '/gapido.auth.v1.AuthService/RequestOtp',
                request_serializer=auth__pb2.RequestOtpRequest.SerializeToString,
                response_deserializer=auth__pb2.RequestOtpResponse.FromString,
                _registered_method=True)
        self.VerifyOtp = channel.unary_unary(
                '/gapido.auth.v1.AuthService/VerifyOtp',
                request_serializer=auth__pb2.VerifyOtpRequest.SerializeToString,
                response_deserializer=auth__pb2.TokenPair.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/gapido.auth.v1.AuthService/RefreshToken',
                request_serializer=auth__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=auth__pb2.TokenPair.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/gapido.auth.v1.AuthService/Logout',
                request_serializer=auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=auth__pb2.LogoutResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """Passwordless phone + OTP authentication.

    Flow:
    1. RequestOtp(phone)          -> OTP is queued to RabbitMQ and delivered by SMS.
    2. VerifyOtp(phone, code)     -> creates the user on first login, returns token pair.
    3. RefreshToken(refresh)      -> rotates the refresh token, returns a new pair.
    4. Logout(refresh)            -> revokes the refresh token family.
    """

    def RequestOtp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOtp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestOtp': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestOtp,
                    request_deserializer=auth__pb2.RequestOtpRequest.FromString,
                    response_serializer=auth__pb2.RequestOtpResponse.SerializeToString,
            ),
            'VerifyOtp': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOtp,
                    request_deserializer=auth__pb2.VerifyOtpRequest.FromString,
                    response_serializer=auth__pb2.TokenPair.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=auth__pb2.RefreshTokenRequest.FromString,
                    response_serializer=auth__pb2.TokenPair.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=auth__pb2.LogoutRequest.FromString,
                    response_serializer=auth__pb2.LogoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gapido.auth.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gapido.auth.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """Passwordless phone + OTP authentication.

    Flow:
    1. RequestOtp(phone)          -> OTP is queued to RabbitMQ and delivered by SMS.
    2. VerifyOtp(phone, code)     -> creates the user on first login, returns token pair.
    3. RefreshToken(refresh)      -> rotates the refresh token, returns a new pair.
    4. Logout(refresh)            -> revokes the refresh token family.
    """

    @staticmethod
    def RequestOtp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gapido.auth.v1.AuthService/RequestOtp',
            auth__pb2.RequestOtpRequest.SerializeToString,
            auth__pb2.RequestOtpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOtp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gapido.auth.v1.AuthService/VerifyOtp',
            auth__pb2.VerifyOtpRequest.SerializeToString,
            auth__pb2.TokenPair.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gapido.auth.v1.AuthService/RefreshToken',
            auth__pb2.RefreshTokenRequest.SerializeToString,
            auth__pb2.TokenPair.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gapido.auth.v1.AuthService/Logout',
            auth__pb2.LogoutRequest.SerializeToString,
            auth__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
