# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import demo_pb2 as demo__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in demo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DemoServiceStub:
    """Three methods exercising the three access levels required by the challenge.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPublicNotice = channel.unary_unary(
                '/gapido.demo.v1.DemoService/GetPublicNotice',
                request_serializer=demo__pb2.Empty.SerializeToString,
                response_deserializer=demo__pb2.PublicNotice.FromString,
                _registered_method=True)
        self.GetMyProfile = channel.unary_unary(
                '/gapido.demo.v1.DemoService/GetMyProfile',
                request_serializer=demo__pb2.Empty.SerializeToString,
                response_deserializer=demo__pb2.Profile.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/gapido.demo.v1.DemoService/ListUsers',
                request_serializer=demo__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=demo__pb2.ListUsersResponse.FromString,
                _registered_method=True)


class DemoServiceServicer:
    """Three methods exercising the three access levels required by the challenge.
    """

    def GetPublicNotice(self, request, context):
        """Accessible by everyone, no token required.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyProfile(self, request, context):
        """Requires a valid access token (any role).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Requires the admin role.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPublicNotice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicNotice,
                    request_deserializer=demo__pb2.Empty.FromString,
                    response_serializer=demo__pb2.PublicNotice.SerializeToString,
            ),
            'GetMyProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyProfile,
                    request_deserializer=demo__pb2.Empty.FromString,
                    response_serializer=demo__pb2.Profile.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=demo__pb2.ListUsersRequest.FromString,
                    response_serializer=demo__pb2.ListUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gapido.demo.v1.DemoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gapido.demo.v1.DemoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DemoService:
    """Three methods exercising the three access levels required by the challenge.
    """

    @staticmethod
    def GetPublicNotice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gapido.demo.v1.DemoService/GetPublicNotice',
            demo__pb2.Empty.SerializeToString,
            demo__pb2.PublicNotice.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gapido.demo.v1.DemoService/GetMyProfile',
            demo__pb2.Empty.SerializeToString,
            demo__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gapido.demo.v1.DemoService/ListUsers',
            demo__pb2.ListUsersRequest.SerializeToString,
            demo__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
