# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x0egapido.demo.v1\"\x07\n\x05\x45mpty\"\x1f\n\x0cPublicNotice\x12\x0f\n\x07message\x18\x01 \x01(\t\"K\n\x07Profile\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\"3\n\x10ListUsersRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"J\n\x11ListUsersResponse\x12&\n\x05users\x18\x01 \x03(\x0b\x32\x17.gapido.demo.v1.Profile\x12\r\n\x05total\x18\x02 \x01(\x03\x32\xe7\x01\n\x0b\x44\x65moService\x12\x46\n\x0fGetPublicNotice\x12\x15.gapido.demo.v1.Empty\x1a\x1c.gapido.demo.v1.PublicNotice\x12>\n\x0cGetMyProfile\x12\x15.gapido.demo.v1.Empty\x1a\x17.gapido.demo.v1.Profile\x12P\n\tListUsers\x12 .gapido.demo.v1.ListUsersRequest\x1a!.gapido.demo.v1.ListUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_PUBLICNOTICE']._serialized_start=39
  _globals['_PUBLICNOTICE']._serialized_end=70
  _globals['_PROFILE']._serialized_start=72
  _globals['_PROFILE']._serialized_end=147
  _globals['_LISTUSERSREQUEST']._serialized_start=149
  _globals['_LISTUSERSREQUEST']._serialized_end=200
  _globals['_LISTUSERSRESPONSE']._serialized_start=202
  _globals['_LISTUSERSRESPONSE']._serialized_end=276
  _globals['_DEMOSERVICE']._serialized_start=279
  _globals['_DEMOSERVICE']._serialized_end=510
# @@protoc_insertion_point(module_scope)
